---
title: "Regional map"
author: "Deanna Beatty"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, include = TRUE, fig.show=TRUE) #global options
```

Package versions

```{r, echo=FALSE, message=FALSE}
library(ggplot2); packageVersion("ggplot2")
library(tidyverse); packageVersion("tidyverse")
library(sf); packageVersion("sf")
library(rnaturalearth); packageVersion("rnaturalearth")
```

```{r, map}

metadata_2019 <- read.table("metadata/fish_metadata_2019.txt", sep = "\t", header = TRUE) 

metadata_2019_subset_SST <- metadata_2019 %>% select(Region, SiteCode, LongestBladeLengthMean, SST, SiteLongitude, SiteLatitude) %>% distinct() %>% na.omit()

metadata_2019_subset_LLLM <- metadata_2019 %>% select(Region, SiteCode, LongestBladeLengthMean, SiteLongitude, SiteLatitude) %>% distinct() %>% na.omit()

# convert to sf object
sites_sf_SST <- st_as_sf(metadata_2019_subset_SST, coords = c("SiteLongitude", "SiteLatitude"), crs = 4326, agr = "constant")
sites_sf_LLLM <- st_as_sf(metadata_2019_subset_LLLM, coords = c("SiteLongitude", "SiteLatitude"), crs = 4326, agr = "constant")
world <- ne_countries(scale = "medium", returnclass = "sf")

map_SST <- ggplot(data = world) + 
  geom_sf(fill="lightgrey")+
  geom_sf(data=sites_sf_SST, aes(color=SST), size=4.7, alpha=0.7) + 
  coord_sf(xlim = c(max(metadata_2019_subset_SST$SiteLongitude), min(metadata_2019_subset_SST$SiteLongitude-4)), 
           ylim = c(max(metadata_2019_subset_SST$SiteLatitude), min(metadata_2019_subset_SST$SiteLatitude)),
           default_crs = sf::st_crs(4326))+
  scale_color_continuous(type="viridis", name="Sea Surface Temperature\n",
                         breaks=c(10, 12, 14, 16, 18, 20))+
  xlab("Longitude")+
  ylab("Latitude")+
  theme_bw(base_size = 16)+
  theme(legend.position = "top", legend.title = element_text(size=12)) +
  theme(axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12)) +
  annotate(geom = "label", size = 3.5,
           x = c(-136, -133, -128.5, -127, -127, -121.5), 
           y = c(55.3, 51.5, 48.5, 44, 38, 32.5),
           # fontface = "italic",
           label = c("Alaska", "British Columbia", "Washington", "Oregon", "Bodega Bay", "San Diego"))
map_SST
# ggsave(map_SST, filename = "output/plots/map_SST.png", dpi = 400, device = "png", width = 8.5, height = 11, units = "in")

map_LLLM <- ggplot(data = world) + 
  geom_sf(fill="gray88")+
  geom_sf(data=sites_sf_LLLM, aes(color=LongestBladeLengthMean), size=4.2, alpha=0.7) + 
  coord_sf(xlim = c(max(metadata_2019_subset_LLLM$SiteLongitude), min(metadata_2019_subset_LLLM$SiteLongitude-4)), 
           ylim = c(max(metadata_2019_subset_LLLM$SiteLatitude), min(metadata_2019_subset_LLLM$SiteLatitude)),
           default_crs = sf::st_crs(4326))+
  scale_color_continuous(type="viridis", name="Longest leaf length mean (mm)\n", breaks=c(100, 500, 1000))+
  xlab("Longitude")+
  ylab("Latitude")+
  theme_bw(base_size = 16)+
  theme(legend.position = "top", legend.title = element_text(size=12)) +
  theme(axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12)) +
  annotate(geom = "label", size = 3.5,
           x = c(-136, -133, -128.5, -127, -127, -121.5), 
           y = c(55.3, 51.5, 48.5, 44, 38, 32.5),
           label = c("Alaska", "British Columbia", "Washington", "Oregon", "Bodega Bay", "San Diego"))
map_LLLM
# ggsave(map_LLLM, filename = "output/plots/map_LLLM.png", dpi = 400, device = "png", width = 8.5, height = 11, units = "in")

```