---
title: "sequence_variant_analysis"
author: "Deanna Beatty"
output: html_document
---

```{r setup} 
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, include = TRUE, fig.show=TRUE) #global options
```

Package versions

```{r, echo=FALSE, message=FALSE}
library(phyloseq); packageVersion("phyloseq")
library(vegan); packageVersion("vegan")
library(ggplot2); packageVersion("ggplot2")
library(tidyverse); packageVersion("tidyverse")
library(ggpubr); packageVersion("ggpubr")
library(ggsci); packageVersion("ggsci")
library(scales); packageVersion("scales")
```

```{r import phyloseq objects, results=FALSE}
Fish_phyloseq_nonrarefied_nonclustered <- readRDS(file = "output/phyloseq_object/Fish_phyloseq_nonrarefied_nonclustered.rds")
Fish_phyloseq_nonclustered_rarefied <- readRDS(file = "output/phyloseq_object/Fish_phyloseq_nonclustered_rarefied.rds")

# order factor levels
sample_data(Fish_phyloseq_nonrarefied_nonclustered)$RegionName <- factor(sample_data(Fish_phyloseq_nonrarefied_nonclustered)$RegionName, levels = c("Alaska", "British Columbia", "Washington", "Oregon", "Bodega", "San Diego"))
sample_data(Fish_phyloseq_nonrarefied_nonclustered)$Region <- factor(sample_data(Fish_phyloseq_nonrarefied_nonclustered)$Region, levels = c("AK", "BC", "WA", "OR", "BB", "SD"))

sample_data(Fish_phyloseq_nonclustered_rarefied)$RegionName <- factor(sample_data(Fish_phyloseq_nonclustered_rarefied)$RegionName, levels = c("Alaska", "British Columbia", "Washington", "Oregon", "Bodega", "San Diego"))
sample_data(Fish_phyloseq_nonclustered_rarefied)$Region <- factor(sample_data(Fish_phyloseq_nonclustered_rarefied)$Region, levels = c("AK", "BC", "WA", "OR", "BB", "SD"))

# remove samples from sites in Bodega that are not part of wasting disease study
remove_list <- c("Sacramento Landing", "Drakes Estero")

Fish_phyloseq_nonrarefied_nonclustered <- subset_samples(Fish_phyloseq_nonrarefied_nonclustered, !(SiteName %in% remove_list))
Fish_phyloseq_nonrarefied_nonclustered

Fish_phyloseq_nonclustered_rarefied <- subset_samples(Fish_phyloseq_nonclustered_rarefied, !(SiteName %in% remove_list))
Fish_phyloseq_nonclustered_rarefied 

# if there are any taxa associated with the phyloseq object that have 0 counts across all remaining samples; remove these
Fish_phyloseq_nonrarefied_nonclustered <- prune_taxa(taxa_sums(Fish_phyloseq_nonrarefied_nonclustered) > 0, Fish_phyloseq_nonrarefied_nonclustered)
Fish_phyloseq_nonrarefied_nonclustered
Fish_phyloseq_nonrarefied_nonclustered_total_sequences = sum(otu_table(Fish_phyloseq_nonrarefied_nonclustered))
nsamples(Fish_phyloseq_nonrarefied_nonclustered)

Fish_phyloseq_nonclustered_rarefied <- prune_taxa(taxa_sums(Fish_phyloseq_nonclustered_rarefied) > 0, Fish_phyloseq_nonclustered_rarefied)
Fish_phyloseq_nonclustered_rarefied 
Fish_phyloseq_nonclustered_rarefied_total_sequences = sum(otu_table(Fish_phyloseq_nonclustered_rarefied))
Fish_phyloseq_nonclustered_rarefied_total_sequences
nsamples(Fish_phyloseq_nonclustered_rarefied)

```

```{r remove non-fish seqs}
non_fish_seqs_data <- read_csv("output/exported-rep_seqs_2019_2020_dada2/non_fish_blast_hits.csv")
unique(non_fish_seqs_data$genus_species)
unique(non_fish_seqs_data$common_name)
length(unique(non_fish_seqs_data$qseqid)) 
non_fish_seq_hashid = unique(non_fish_seqs_data$qseqid)

non_fish_seq_hashid_present_Fish_phyloseq_nonrarefied_nonclustered = non_fish_seq_hashid[non_fish_seq_hashid %in% taxa_names(Fish_phyloseq_nonrarefied_nonclustered)]
non_fish_seq_hashid_present_Fish_phyloseq_nonrarefied_nonclustered

non_fish_seq_hashid_present_Fish_phyloseq_nonclustered_rarefied = non_fish_seq_hashid[non_fish_seq_hashid %in% taxa_names(Fish_phyloseq_nonclustered_rarefied)]
non_fish_seq_hashid_present_Fish_phyloseq_nonclustered_rarefied

Fish_phyloseq_nonrarefied_nonclustered_filtered <- prune_taxa(!(taxa_names(Fish_phyloseq_nonrarefied_nonclustered) %in% non_fish_seq_hashid), Fish_phyloseq_nonrarefied_nonclustered)
Fish_phyloseq_nonrarefied_nonclustered
Fish_phyloseq_nonrarefied_nonclustered_filtered
Fish_phyloseq_nonrarefied_nonclustered_filtered_total_sequences = sum(otu_table(Fish_phyloseq_nonrarefied_nonclustered_filtered))
Fish_phyloseq_nonrarefied_nonclustered_filtered_total_sequence
Fish_phyloseq_nonrarefied_nonclustered_total_sequences

percent_seqs_removed_nonrarefied_nonclustered = ((Fish_phyloseq_nonrarefied_nonclustered_total_sequences - Fish_phyloseq_nonrarefied_nonclustered_filtered_total_sequences)/Fish_phyloseq_nonrarefied_nonclustered_total_sequences)
percent_seqs_removed_nonrarefied_nonclustered
percent_fish_sequences_of_total_following_dada2 = (1-percent_seqs_removed_nonrarefied_nonclustered)*100
percent_fish_sequences_of_total_following_dada2

any(non_fish_seq_hashid %in% taxa_names(Fish_phyloseq_nonrarefied_nonclustered_filtered))

Fish_phyloseq_nonclustered_rarefied_filtered <- prune_taxa(!(taxa_names(Fish_phyloseq_nonclustered_rarefied) %in% non_fish_seq_hashid), Fish_phyloseq_nonclustered_rarefied)
Fish_phyloseq_nonclustered_rarefied
Fish_phyloseq_nonclustered_rarefied_filtered
Fish_phyloseq_nonclustered_rarefied_total_sequences = sum(otu_table(Fish_phyloseq_nonclustered_rarefied))
Fish_phyloseq_nonclustered_rarefied_filtered_total_sequences = sum(otu_table(Fish_phyloseq_nonclustered_rarefied_filtered))
percent_seqs_removed_nonclustered_rarefied = (Fish_phyloseq_nonclustered_rarefied_total_sequences-Fish_phyloseq_nonclustered_rarefied_filtered_total_sequences)/Fish_phyloseq_nonclustered_rarefied_total_sequences
percent_seqs_removed_nonclustered_rarefied

any(non_fish_seq_hashid %in% taxa_names(Fish_phyloseq_nonclustered_rarefied_filtered))

```

```{r betadiv on rarefied data}
# subset to 2019 data
Fish_phyloseq_nonclustered_rarefied_filtered_2019 <- subset_samples(Fish_phyloseq_nonclustered_rarefied_filtered, Year == "2019")
Fish_phyloseq_nonclustered_rarefied_filtered_2019

# with SST data
# subset to samples with SST data
fish_2019_phyloseq_SST <- Fish_phyloseq_nonclustered_rarefied_filtered_2019 %>% 
  subset_samples(!is.na(SST))
fish_2019_phyloseq_SST

# extract metadata as dataframe
metadata_2019_SST <- data.frame(sample_data(fish_2019_phyloseq_SST))

# bray curtis dissimilarity
fish_2019_SST_bray <- distance(fish_2019_phyloseq_SST, method = "bray")
# jaccard dissimilarity
fish_2019_SST_jaccard <- distance(fish_2019_phyloseq_SST, method = "jaccard")

# pcoa ordination
fish_2019_SST_bray_ord <- ordinate(fish_2019_phyloseq_SST, method = "PCoA", distance = fish_2019_SST_bray)
fish_2019_SST_jaccard_ord <- ordinate(fish_2019_phyloseq_SST, method = "PCoA", distance = fish_2019_SST_jaccard)

# adonis2 
fish_2019_SST_bray_adonis <- adonis2(fish_2019_SST_bray ~ PrevalenceMean + SeverityMean + DensityShootsMean + LongestBladeLengthMean + SST + Region, data = metadata_2019_SST)
fish_2019_SST_bray_adonis
write.csv(fish_2019_SST_bray_adonis, "output/stats/fish_2019_bray_adonis_nonclustered_rarefied.csv")

fish_2019_SST_jaccard_adonis <- adonis2(fish_2019_SST_jaccard ~ PrevalenceMean + SeverityMean + DensityShootsMean + LongestBladeLengthMean + SST + Region, data = metadata_2019_SST)
fish_2019_SST_jaccard_adonis
write.csv(fish_2019_SST_jaccard_adonis, "output/stats/fish_2019_jaccard_adonis_nonclustered_rarefied.csv")

# factors
fish_factor <- c("Lesion prevalence mean", "Lesion severity mean", "Shoot density Mean", "Longest leaf length mean", "SST", "Region", "Residual", "Total")
adonis_df <- data.frame(fish_2019_SST_bray_adonis$Df, fish_2019_SST_bray_adonis$SumOfSqs,
                        fish_2019_SST_bray_adonis$R2, fish_2019_SST_bray_adonis$F,
                        fish_2019_SST_bray_adonis$`Pr(>F)`)
adonis_df$Factor <- fish_factor
adonis_df <- adonis_df[ , c(6,1,2,3,4,5)]
adonis_df <- rename(adonis_df, "Pr(>F)" = fish_2019_SST_bray_adonis..Pr..F.., "F"=fish_2019_SST_bray_adonis.F, R2 = fish_2019_SST_bray_adonis.R2, SumOfSqs = fish_2019_SST_bray_adonis.SumOfSqs, Df = fish_2019_SST_bray_adonis.Df)
write.csv(adonis_df, "output/stats/fish_2019_bray_adonis_nonclustered_rarefied_formatted.csv")

#plot by longest blade length mean
fish_2019_bray_ord_PCoA_LLLM <- plot_ordination(fish_2019_phyloseq_SST,fish_2019_SST_bray_ord) + 
  geom_point(mapping = aes(color = LongestBladeLengthMean,  shape = Region), size = 6, stroke = 2) +
  scale_color_viridis_c(direction = -1) +
  scale_shape_manual(values=c(8, 15, 3, 17, 18, 16)) +
  theme_classic() +
  theme(legend.title = element_text(size=14), legend.text = element_text(size=14), axis.text=element_text(size=14), axis.title = element_text(size = 14) ) +
  labs(shape = "Region", color = "Longest leaf length mean (mm)") +
  guides(color = guide_legend(override.aes = list(size=4)), shape = guide_legend(override.aes = list(size=4)))

fish_2019_bray_ord_PCoA_LLLM

ggsave(fish_2019_bray_ord_PCoA_LLLM, file = "output/plots/fish_2019_nonclustered_rarefied_bray_ord_PCoA_LLLM.png", dpi = 400, device = "png", width = 11, height = 8.5, units = "in")

```

```{r sequence variants}
# non-rarefied and non-clustered data 
# melt phyloseq object to df
Fish_nonrarefied_nonclustered <- psmelt(Fish_phyloseq_nonrarefied_nonclustered_filtered)
total_seq_count = sum(Fish_nonrarefied_nonclustered$Abundance)
total_seq_count

length(unique(Fish_nonrarefied_nonclustered$OTU))
Fish_nonrarefied_nonclustered_seq_variants_spp_assignments <- filter(Fish_nonrarefied_nonclustered, !is.na(Species))
length(unique(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments$OTU))
total_seq_count_with_species_id_97_per_sim = sum(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments$Abundance)
total_seq_count_with_species_id_97_per_sim

total_seq_count_with_species_id_97_per_sim/total_seq_count

length(unique(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments$Species))
unique(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments$Species)
eDNA_species_2019_2020 <- as.data.frame(unique(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments$Species))
names(eDNA_species_2019_2020)[1] <- "Taxonomy"

species_subset <- subset(Fish_nonrarefied_nonclustered_seq_variants_spp_assignments, select = c(Abundance, Species, SiteName, Region, Year, Sample, OTU))  %>% arrange(Sample)
sp_table = list()
spp_assigned_sv = unique(species_subset$Species)

for (i in seq_along(spp_assigned_sv)) {
  temp = filter(species_subset, Species == spp_assigned_sv[i])
  number_sv = length(unique(temp$OTU))
  name = spp_assigned_sv[i]
  row = data.frame(Species = name, Number_of_sequence_variants = number_sv)
  sp_table[[i]] <- row
}

# bind items in list with bind_rows
sp_table_sv <- bind_rows(sp_table)

# write.csv("output/stats/sequence_variants_per_species.csv")

Fish_2019 <- Fish_nonrarefied_nonclustered %>% filter(Year == "2019") %>% filter(Abundance != "0")
length(unique(Fish_2019$OTU))
sum(Fish_2019$Abundance)

Fish_2020 <- Fish_nonrarefied_nonclustered %>% filter(Year == "2020") %>% filter(Abundance != "0")
length(unique(Fish_2020$OTU))
sum(Fish_2020$Abundance)

# unique sequence variants for each region
AK <- Fish_2019 %>% filter(Region == "AK") %>% filter(Abundance != "0")
BC <- Fish_2019 %>% filter(Region == "BC") %>% filter(Abundance != "0")
WA <- Fish_2019 %>% filter(Region == "WA") %>% filter(Abundance != "0")
OR <- Fish_2019 %>% filter(Region == "OR") %>% filter(Abundance != "0")
BB <- Fish_2019 %>% filter(Region == "BB") %>% filter(Abundance != "0")
SD <- Fish_2019 %>% filter(Region == "SD") %>% filter(Abundance != "0")

BB_2020 <- Fish_2020 %>% filter(Abundance != "0")

AK_sv <- length(unique(AK$OTU))
AK_sv

BC_sv <- length(unique(BC$OTU))
BC_sv

WA_sv <- length(unique(WA$OTU))
WA_sv

OR_sv <- length(unique(OR$OTU))
OR_sv

BB_sv <- length(unique(BB$OTU))
BB_sv

SD_sv <- length(unique(SD$OTU))
SD_sv

```

```{r sequence variant accum vegan}

# subset to columns abundance, sample, OTU
df_sub <- subset(Fish_nonrarefied_nonclustered, select = c(Abundance, Sample, OTU))
# pivot wider
df_sub_w <- df_sub %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
# sample as row names
row.names(df_sub_w) <- df_sub_w$Sample
# remove sample column
df_sp_all <- subset(df_sub_w, select = -c(Sample))
df_sp_all[is.na(df_sp_all)] <- 0

# spec accum for all data
SpAccAll <- specaccum(df_sp_all, method = "random")
summary(SpAccAll)
plot(SpAccAll, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccAll)
SpAccAll

#creating a dataframe for ggplot2
SpAccAlldf <- data.frame(Sites=as.numeric(SpAccAll$sites), Richness=SpAccAll$richness, SD=SpAccAll$sd)
SpAccAlldf$Sites <- order(SpAccAlldf$Sites)

ggplot(SpAccAlldf, aes(x = Richness)) + geom_histogram()

eDNA_sv_acumm <- ggplot(data=SpAccAlldf, aes(x=Sites, y=Richness)) +
  geom_point(aes(x=Sites, y=Richness)) +
  geom_line(aes(x=Sites, y=Richness)) +
  geom_ribbon(aes(x=Sites, ymin=(Richness-SD),ymax=(Richness+SD)),alpha=0.2) +
  theme(axis.text=element_text(size=18), axis.title = element_text(size = 18) ) +
  ylab("Sequence variant richness") +
  xlab("Sample size")

eDNA_sv_acumm

# repeat on 2019 samples only
# subset to columns abundance, sample, OTU
Fish_2019_sub <- subset(Fish_2019, select = c(Abundance, Sample, OTU))
# pivot wider
Fish_2019_sub_w <- Fish_2019_sub %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
# make column Sample to row names
Fish_2019_sp <- Fish_2019_sub_w %>% remove_rownames %>% column_to_rownames(var="Sample")
Fish_2019_sp[is.na(Fish_2019_sp)] <- 0

# spec accum 
SpAccFish2019 <- specaccum(comm=Fish_2019_sp, method = "random")
summary(SpAccFish2019)
plot(SpAccFish2019, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccFish2019)
SpAccFish2019

#creating a dataframe for ggplot2
SpAccFish2019df <- data.frame(Sites=as.numeric(SpAccFish2019$sites), Richness=SpAccFish2019$richness, SD=SpAccFish2019$sd)
SpAccFish2019df$Sites <- order(SpAccFish2019df$Sites)

eDNA_sv_acumm_2019 <- ggplot(data=SpAccFish2019df) +
  geom_point(aes(x=Sites, y=Richness)) +
  geom_line(aes(x=Sites, y=Richness)) +
  scale_colour_manual(values = "darkgray") +
  scale_x_continuous(breaks=c(0,10,20,30,40,50,60, 70, 80,90), limits = c(0, 90)) +
  geom_ribbon(aes(x=Sites, ymin=(Richness-SD),ymax=(Richness+SD)),alpha=0.2) +
  theme(axis.text=element_text(size=16), axis.title = element_text(size = 18) ) +
  theme_classic() +
  ylab("Sequence variant richness") +
  xlab("Sample size")

eDNA_sv_acumm_2019

# AK format data
df_AK <- filter(Fish_2019, Region == "AK")
df_AK <- subset(df_AK, select = c(Abundance, Sample, OTU))
df_AK_w <- df_AK %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_AK_w <- subset(df_AK_w, select = -c(Sample))
df_AK_w[is.na(df_AK_w)] <- 0

# specaccum
SpAccAK <- specaccum(df_AK_w, method = "random")
summary(SpAccAK)
plot(SpAccAK, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccAK)
SpAccAK

#creating a dataframe for ggplot2
SpAccAKdf <- data.frame(Sites=as.numeric(SpAccAK$sites), Richness=SpAccAK$richness, SD=SpAccAK$sd)
SpAccAKdf$Sites <- order(SpAccAKdf$Sites)
SpAccAKdf$Region <- c("AK")

eDNA_sv_acumm_AK <- ggplot(data=SpAccAKdf) +
  geom_point(aes(x=Sites, y=Richness)) +
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)) +
  geom_line(aes(x=Sites, y=Richness)) +
  geom_ribbon(aes(x=Sites, ymin=(Richness-SD),ymax=(Richness+SD)),alpha=0.2) +
  theme(axis.text=element_text(size=14), axis.title = element_text(size = 14)) +
  ylab("OTU richness") +
  xlab("Sample size")

eDNA_sv_acumm_AK

# BC format data
df_BC <- filter(Fish_2019, Region == "BC")
df_BC <- subset(df_BC, select = c(Abundance, Sample, OTU))
df_BC_w <- df_BC %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_BC_w <- subset(df_BC_w, select = -c(Sample))
df_BC_w[is.na(df_BC_w)] <- 0

# specaccum
SpAccBC <- specaccum(df_BC_w, method = "random")
summary(SpAccBC)
plot(SpAccBC, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccBC)
SpAccBC

#creating a dataframe for ggplot2
SpAccBCdf <- data.frame(Sites=as.numeric(SpAccBC$sites), Richness=SpAccBC$richness, SD=SpAccBC$sd)
SpAccBCdf$Sites <- order(SpAccBCdf$Sites)
SpAccBCdf$Region <- c("BC")

# WA format data
df_WA <- filter(Fish_2019, Region == "WA")
df_WA <- subset(df_WA, select = c(Abundance, Sample, OTU))
df_WA_w <- df_WA %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_WA_w <- subset(df_WA_w, select = -c(Sample))
df_WA_w[is.na(df_WA_w)] <- 0

# specaccum
SpAccWA <- specaccum(df_WA_w, method = "random")
summary(SpAccWA)
plot(SpAccWA, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccWA)
SpAccWA

#creating a dataframe for ggplot2
SpAccWAdf <- data.frame(Sites=as.numeric(SpAccWA$sites), Richness=SpAccWA$richness, SD=SpAccWA$sd)
SpAccWAdf$Sites <- order(SpAccWAdf$Sites)
SpAccWAdf$Region <- c("WA")

# OR format data
df_OR <- filter(Fish_2019, Region == "OR")
df_OR <- subset(df_OR, select = c(Abundance, Sample, OTU))
df_OR_w <- df_OR %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_OR_w <- subset(df_OR_w, select = -c(Sample))
df_OR_w[is.na(df_OR_w)] <- 0

# specaccum
SpAccOR <- specaccum(df_OR_w, method = "random")
summary(SpAccOR)
plot(SpAccOR, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccOR)
SpAccOR

#creating a dataframe for ggplot2
SpAccORdf <- data.frame(Sites=as.numeric(SpAccOR$sites), Richness=SpAccOR$richness, SD=SpAccOR$sd)
SpAccORdf$Sites <- order(SpAccORdf$Sites)
SpAccORdf$Region <- c("OR")

# BB format data
df_BB <- filter(Fish_2019, Region == "BB")
df_BB <- subset(df_BB, select = c(Abundance, Sample, OTU))
df_BB_w <- df_BB %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_BB_w <- subset(df_BB_w, select = -c(Sample))
df_BB_w[is.na(df_BB_w)] <- 0

# specaccum
SpAccBB <- specaccum(df_BB_w, method = "random")
summary(SpAccBB)
plot(SpAccBB, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccBB)
SpAccBB

#creating a dataframe for ggplot2
SpAccBBdf <- data.frame(Sites=as.numeric(SpAccBB$sites), Richness=SpAccBB$richness, SD=SpAccBB$sd)
SpAccBBdf$Sites <- order(SpAccBBdf$Sites)
SpAccBBdf$Region <- c("BB")

# SD format data
df_SD <- filter(Fish_2019, Region == "SD")
df_SD <- subset(df_SD, select = c(Abundance, Sample, OTU))
df_SD_w <- df_SD %>%
  pivot_wider(names_from = OTU, values_from = Abundance)
df_SD_w <- subset(df_SD_w, select = -c(Sample))
df_SD_w[is.na(df_SD_w)] <- 0

# specaccum
SpAccSD <- specaccum(df_SD_w, method = "random")
summary(SpAccSD)
plot(SpAccSD, ci.type="poly", col="darkblue", lwd=2, ci.lty=0, ci.col="lightblue")
boxplot(SpAccSD)
SpAccSD

#creating a dataframe for ggplot2
SpAccSDdf <- data.frame(Sites=as.numeric(SpAccSD$sites), Richness=SpAccSD$richness, SD=SpAccSD$sd)
SpAccSDdf$Sites <- order(SpAccSDdf$Sites)
SpAccSDdf$Region <- c("SD")

# rbind estuary dfs
all_regions_specaccum <- rbind(SpAccAKdf, SpAccBCdf, SpAccWAdf, SpAccORdf, SpAccBBdf, SpAccSDdf)
all_regions_specaccum$Region <- factor(all_regions_specaccum$Region, levels = c("AK", "BC", "WA", "OR", "BB", "SD"))

# assign hexidecimal color codes to variable
mypal_locuszoom <- pal_locuszoom("default")(7)
show_col(mypal_locuszoom)

eDNA_sv_acumm_all_regions <- ggplot(data=all_regions_specaccum, mapping = aes(color = Region)) +
  geom_point(aes(x=Sites, y=Richness)) +
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10,11, 12, 13, 14, 15,16,17,18)) +
  scale_y_continuous(breaks=c(100,200,300,400,500,600), limits = c(0,600)) +
  scale_colour_manual(values = mypal_locuszoom) +
  geom_line(aes(x=Sites, y=Richness)) +
  geom_ribbon(aes(x=Sites, ymin=(Richness-SD),ymax=(Richness+SD)),alpha=0.1) +
  theme(axis.text=element_text(size=16), axis.title = element_text(size = 18)) +
  theme_classic() +
  ylab("Sequence variant richness") +
  xlab("Sample size")

eDNA_sv_acumm_all_regions

Figure_sequence_variant_acumm_stack <- ggarrange(eDNA_sv_acumm_2019,eDNA_sv_acumm_all_regions, labels = c("A", "B"), ncol = 1, nrow = 2, align = "hv", heights = c(1,1))
Figure_sequence_variant_acumm_stack
ggsave(Figure_sequence_variant_acumm_stack, file = "output/plots/Figure_sequence_variant_acumm_stack_2019.png", 
        dpi = 400, device = "png", width = 11, height = 8.5, units = "in")

```